using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;
using TMPro;
using UnityEngine.UI;

/// <summary>
/// Class to manage UFO Catcher camera switching and keyboard control modes.
/// </summary>
public class UFOCameraController : MonoBehaviour
{
    public static UFOCameraController Instance { get; private set; }
    public static bool IsPlayingUfo { get; private set; } = false;
    public static bool IsPlaySessionActive { get; private set; } = false;
    public static bool IsControlActive => IsPlaySessionActive && IsPlaySpotlightActive && Instance != null && Instance._playTimer > 0f;

    [Header("Camera Settings")]
    [Tooltip("Player's first-person camera")]
    [SerializeField] private Camera playerCamera;

    [Tooltip("UFO Catcher front view camera (autodetected if null)")]
    [SerializeField] private Camera frontCamera;

    [Tooltip("Left view camera (autogenerated if null)")]
    [SerializeField] private Camera leftCamera;

    [Tooltip("Right view camera (autogenerated if null)")]
    [SerializeField] private Camera rightCamera;

    [Tooltip("Top view camera (autogenerated if null)")]
    [SerializeField] private Camera topCamera;

    [Header("UI Settings")]
    [Tooltip("UFO Catcher UI Canvas/Object to hide when not playing")]
    [SerializeField] private GameObject ufoUiCanvas;

    [Header("Cost / Timer / Spotlight Settings")]
    [Tooltip("Base play cost")]
    [SerializeField] private float playCostBase = 100f;

    [Tooltip("Control time limit per play (seconds)")]
    [SerializeField] private float playDuration = 30f;

    [Tooltip("Max play count per session")]
    [SerializeField] private int maxPlayCount = 3;

    [Tooltip("Multiplier by which the cost increases per play")]
    [SerializeField] private float costIncreaseMultiplier = 1.5f;

    [Tooltip("Spotlight GameObject enabled only during active play session")]
    [SerializeField] private GameObject playSpotlight;

    [Header("Audio Settings")]
    [Tooltip("再生用のAudioSource。未設定の場合は自動でGetComponentします")]
    [SerializeField] private AudioSource audioSource;
    [Tooltip("コイン投入時（ゲーム開始時）の効果音")]
    [SerializeField] private AudioClip coinInsertSound;
    [Tooltip("残り10秒を切ったとき（警告時）の効果音")]
    [SerializeField] private AudioClip lowTimeWarningSound;
    [Tooltip("効果音の音量調整 (1.0より大きい値で音量増幅可能)")]
    [Range(0f, 10f)]
    [SerializeField] private float soundVolume = 1.0f;

    [Header("Interaction Settings")]
    [Tooltip("Interaction distance to start playing")]
    [SerializeField] private float interactionDistance = 3.5f;

    [Tooltip("Reference Transform for UFO center (autodetected if null)")]
    [SerializeField] private Transform ufoCenterTransform;

    [Header("Camera Transition Settings")]
    [Tooltip("UFOキャッチャー台にアタッチした MouseHoverOutline。ホバー判定とクリック開始に使う")]
    [SerializeField] private MouseHoverOutline machineHover;

    [Min(0.01f)]
    [Tooltip("カメラ移動の所要時間（秒）")]
    [SerializeField] private float transitionDuration = 1.0f;

    [Tooltip("移動の緩急（0→1）")]
    [SerializeField] private AnimationCurve transitionEase = AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);

    [Header("Coin Play Animation Settings")]
    [Tooltip("コイン投入演出で出現させるコインのPrefab")]
    [SerializeField] private GameObject coinPrefab;

    [Tooltip("コインの親とするDEVILCATCHERオブジェクト名")]
    [SerializeField] private string devilCatcherName = "DEVILCATCHER";

    [Tooltip("コイン出現時のローカル座標")]
    [SerializeField] private Vector3 coinStartLocalPos = new Vector3(10.5422926f, 10.5422945f, 10.5422926f);

    [Tooltip("コイン移動終了時のローカル座標（ここから放します）")]
    [SerializeField] private Vector3 coinEndLocalPos = new Vector3(10.5422926f, 10.5422945f, 10.5422926f);

    [Tooltip("生成するコインのスケール")]
    [SerializeField] private Vector3 coinAnimationScale = new Vector3(10.5422926f, 10.5422945f, 10.5422926f);

    [Tooltip("コインの移動時間（秒）")]
    [SerializeField] private float coinAnimationDuration = 1.0f;

    [Tooltip("生成するコインの初期ローカル角度（オイラー角）")]
    [SerializeField] private Vector3 coinAnimationRotation = new Vector3(0f, -90f, 0f);

    [Tooltip("TriggerSoundPlayer反応時のコイン投入演出リピート回数")]
    [SerializeField] private int coinAnimationRepeatCount = 3;

    [Tooltip("制御対象とするUFOキャッチャーのライトオブジェクト群（ヒエラルキーからアタッチします）")]
    [SerializeField] private GameObject[] targetLights;

    [Header("Light Audio Settings")]
    [Tooltip("ライト点滅時のチカッという音")]
    [SerializeField] private AudioClip lightFlickerSound;
    [Tooltip("点滅（起動）音の音量")]
    [SerializeField] [Range(0f, 10f)] private float lightFlickerVolume = 0.5f;
    [Tooltip("ライト消灯時のカチッという音")]
    [SerializeField] private AudioClip lightOffSound;
    [Tooltip("消灯音の音量")]
    [SerializeField] [Range(0f, 10f)] private float lightOffVolume = 0.5f;

    /// <summary>
    /// 指定された効果音を筐体メインのaudioSourceの位置から、末尾を指定秒数カットした状態で2D再生します。
    /// </summary>
    private void PlayLightSoundWithTailCut(AudioClip clip, float volume, float cutDuration)
    {
        if (clip == null) return;

        // メインスピーカーのGameObjectを親にして、一時的な再生オブジェクトを作成（一箇所再生を維持）
        GameObject tempAudioObj = new GameObject("TempLightAudioSource");
        if (audioSource != null)
        {
            tempAudioObj.transform.SetParent(audioSource.transform, false);
        }
        else
        {
            tempAudioObj.transform.SetParent(transform, false);
        }

        AudioSource tempSource = tempAudioObj.AddComponent<AudioSource>();
        tempSource.clip = clip;
        tempSource.volume = volume;
        tempSource.spatialBlend = 0.0f; // 2D再生
        tempSource.playOnAwake = false;
        tempSource.loop = false;

        tempSource.Play();

        // (効果音の長さ - カット秒数) 秒だけ再生して停止・破棄する
        float playDuration = Mathf.Max(0f, clip.length - cutDuration);
        StartCoroutine(StopAndDestroyAudioCoroutine(tempAudioObj, tempSource, playDuration));
    }

    private System.Collections.IEnumerator StopAndDestroyAudioCoroutine(GameObject audioObj, AudioSource source, float delay)
    {
        yield return new WaitForSeconds(delay);
        if (source != null)
        {
            source.Stop();
        }
        if (audioObj != null)
        {
            Destroy(audioObj);
        }
    }

    /// <summary>
    /// 現在スポットライトおよび連動ライトが有効（点灯）になっているかどうか
    /// </summary>
    public static bool IsPlaySpotlightActive { get; private set; } = false;

    private App.Player.FirstPersonController _fpController;
    private UFOArmController _ufoController;
    private Camera _activeCamera;
    private bool _showPrompt = false;
    private Texture2D _bgTexture;

    // 元のライト強度を保存する辞書
    private System.Collections.Generic.Dictionary<Light, float> _originalLightIntensities = new System.Collections.Generic.Dictionary<Light, float>();
    // 元のライト範囲を保存する辞書
    private System.Collections.Generic.Dictionary<Light, float> _originalLightRanges = new System.Collections.Generic.Dictionary<Light, float>();

    /// <summary>
    /// 制御対象となるすべてのライトの元の強度と照射範囲をキャッシュします。
    /// </summary>
    private void CacheOriginalLightIntensities()
    {
        _originalLightIntensities.Clear();
        _originalLightRanges.Clear();

        if (playSpotlight != null)
        {
            foreach (var light in playSpotlight.GetComponentsInChildren<Light>(true))
            {
                if (light != null && !_originalLightIntensities.ContainsKey(light))
                {
                    _originalLightIntensities[light] = light.intensity;
                    _originalLightRanges[light] = light.range;
                }
            }
        }

        if (targetLights != null)
        {
            foreach (var obj in targetLights)
            {
                if (obj != null)
                {
                    foreach (var light in obj.GetComponentsInChildren<Light>(true))
                    {
                        if (light != null && !_originalLightIntensities.ContainsKey(light))
                        {
                            _originalLightIntensities[light] = light.intensity;
                            _originalLightRanges[light] = light.range;
                        }
                    }
                }
            }
        }
    }

    private int _paymentCount = 0;
    private float _playTimer = 0f;
    private int _triggeredCoinCount = 0;
    private int _destroyedCoinCount = 0;
    private float _feverTimer = 0f; // フィーバータイム残り時間

    /// <summary>
    /// フィーバータイム（制限時間ストップ）が現在有効かどうか
    /// </summary>
    public static bool IsFeverTimeActive => Instance != null && Instance._feverTimer > 0f;

    private bool _isTransitioning = false;
    private bool _hasPlayedLowTimeWarning = false;
    private Vector3 _originalPlayerCamPos;
    private Quaternion _originalPlayerCamRot;

    // 動的UI要素
    private Canvas _dynamicCanvas;
    private TextMeshProUGUI _promptText;
    private GameObject _paymentPanel;
    private TextMeshProUGUI _paymentStatusText;
    private UnityEngine.UI.Button _payButton;
    private TextMeshProUGUI _payButtonText;
    private GameObject _timerPanel;
    private TextMeshProUGUI _timerText;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }
        else
        {
            Debug.LogWarning("[UFOCameraController] Multiple instances of UFOCameraController detected in the scene.");
        }
    }

    /// <summary>
    /// Returns the currently active camera.
    /// </summary>
    public Camera GetActiveCamera()
    {
        if (IsPlayingUfo && _activeCamera != null)
        {
            return _activeCamera;
        }
        return playerCamera != null ? playerCamera : Camera.main;
    }

    private void Start()
    {
        // プレイヤーとUFOキャッチャーのアームコントローラーを自動検出
        _fpController = FindAnyObjectByType<App.Player.FirstPersonController>();
        _ufoController = GetComponent<UFOArmController>();
        if (_ufoController == null)
        {
            _ufoController = GetComponentInChildren<UFOArmController>(true);
        }
        if (_ufoController == null)
        {
            _ufoController = GetComponentInParent<UFOArmController>(true);
        }
        if (_ufoController == null)
        {
            _ufoController = FindAnyObjectByType<UFOArmController>();
        }

        if (ufoCenterTransform == null)
        {
            ufoCenterTransform = transform;
        }

        if (_fpController != null && playerCamera == null)
        {
            playerCamera = _fpController.GetComponentInChildren<Camera>(true);
        }

        // ===== デバッグログ =====
        Debug.Log($"[UFOCameraController] Start: fpController={(_fpController != null ? _fpController.name : "NULL")}");
        Debug.Log($"[UFOCameraController] Start: playerCamera={( playerCamera != null ? playerCamera.name : "NULL")}");
        Debug.Log($"[UFOCameraController] Start: ufoCenterTransform={ufoCenterTransform.name}");
        Debug.Log($"[UFOCameraController] Start: interactionDistance={interactionDistance}");
        // =======================

        SetupDynamicCameras();

        // 動的UIの生成
        CreateDynamicUI();

        // AudioSourceの自動取得
        if (audioSource == null)
        {
            audioSource = GetComponent<AudioSource>();
        }

        // 開始時はUFOプレイモードではない状態にする
        SetUfoMode(false);

        // 開始時はライトをオフにしておく
        SetPlaySpotlight(false);

        if (machineHover != null)
        {
            machineHover.OnClicked += OnMachineClicked;
        }
    }

    private void SetupDynamicCameras()
    {
        if (frontCamera == null)
        {
            frontCamera = transform.Find("Ufo_camera")?.GetComponent<Camera>();
            if (frontCamera == null)
            {
                // 子オブジェクトからカメラを検索
                frontCamera = GetComponentInChildren<Camera>(true);
            }
        }

        if (frontCamera == null)
        {
            Debug.LogWarning("[UFOCameraController] 正面カメラ (frontCamera) が見つかりません。自動生成用カメラをベースにできません。");
            return;
        }

        // オーディオマネージャー等の警告対策として、UFO側のカメラのAudioListenerは無効化しておく
        var listener = frontCamera.GetComponent<AudioListener>();
        if (listener != null) listener.enabled = false;

        // 左側カメラの自動生成
        if (leftCamera == null)
        {
            leftCamera = CreateCopyCamera("Ufo_camera_left");
            leftCamera.transform.SetParent(ufoCenterTransform, false);
            // 正面 (9.98, 6.86, -3.465) から見て左側 (Z負方向) に配置
            leftCamera.transform.localPosition = new Vector3(0f, 6.86f, -13.465f);
            leftCamera.transform.localEulerAngles = new Vector3(25f, 0f, 0f);
        }

        // 右側カメラの自動生成
        if (rightCamera == null)
        {
            rightCamera = CreateCopyCamera("Ufo_camera_right");
            rightCamera.transform.SetParent(ufoCenterTransform, false);
            // 正面から見て右側 (Z正方向) に配置
            rightCamera.transform.localPosition = new Vector3(0f, 6.86f, 6.535f);
            rightCamera.transform.localEulerAngles = new Vector3(25f, 180f, 0f);
        }

        // 上部カメラの自動生成
        if (topCamera == null)
        {
            topCamera = CreateCopyCamera("Ufo_camera_top");
            topCamera.transform.SetParent(ufoCenterTransform, false);
            // 真上から見下ろす配置
            topCamera.transform.localPosition = new Vector3(0f, 12f, -3.465f);
            topCamera.transform.localEulerAngles = new Vector3(90f, -90f, 0f);
        }
    }

    private Camera CreateCopyCamera(string name)
    {
        GameObject go = new GameObject(name);
        Camera newCam = go.AddComponent<Camera>();

        // 正面カメラの設定を複製
        newCam.fieldOfView = frontCamera.fieldOfView;
        newCam.nearClipPlane = frontCamera.nearClipPlane;
        newCam.farClipPlane = frontCamera.farClipPlane;
        newCam.cullingMask = frontCamera.cullingMask;
        newCam.clearFlags = frontCamera.clearFlags;
        newCam.backgroundColor = frontCamera.backgroundColor;
        newCam.depth = frontCamera.depth - 1; // プレイヤーカメラの下にするため低めに設定
        newCam.targetDisplay = frontCamera.targetDisplay; // Display2など使用中のDisplayに合わせる
        newCam.enabled = false;
        go.tag = frontCamera.tag; // タグ（MainCamera等）を引き継ぐ

        // URP対応：UniversalAdditionalCameraData のコピー
        var srcData = frontCamera.GetComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();
        if (srcData != null)
        {
            var destData = go.AddComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();
            destData.renderShadows = srcData.renderShadows;
            destData.requiresDepthOption = srcData.requiresDepthOption;
            destData.requiresColorOption = srcData.requiresColorOption;
            destData.renderPostProcessing = srcData.renderPostProcessing;
            destData.antialiasing = srcData.antialiasing;
        }

        // AudioListenerがあれば無効化
        var listener = go.GetComponent<AudioListener>();
        if (listener != null) listener.enabled = false;

        return newCam;
    }

    private void Update()
    {
        if (_fpController == null)
        {
            _fpController = FindAnyObjectByType<App.Player.FirstPersonController>();
            if (_fpController == null) return;
        }

        // プレイヤーの当たり判定（CharacterControllerのカプセル体）の表面とUFOキャッチャー中心との最短距離を計算
        float distance = GetDistanceToPlayer(_fpController, ufoCenterTransform.position);
        bool isClose = distance <= interactionDistance;

        // ===== デバッグログ（毎秒1回だけ表示）=====
        if (Time.frameCount % 60 == 0)
        {
            Debug.Log($"[UFOCameraController] 距離: {distance:F2} / 判定距離: {interactionDistance} / 近い: {isClose} / プレイ中: {IsPlayingUfo} / タイマー: {_playTimer:F1}");
        }
        // ===========================================

        if (!IsPlayingUfo)
        {
            bool canPlayUfo = RoundManager.Instance == null || RoundManager.Instance.CanPlayUfo();

            // プレイ可能かつ遷移中でない場合のみ、ホバーアウトラインを有効化する
            if (machineHover != null)
            {
                machineHover.enabled = canPlayUfo && !_isTransitioning;
            }

            // プレイ不可かつ近くにいる場合のみ、ロックされている旨を表示
            if (!canPlayUfo && isClose)
            {
                _showPrompt = true;
                if (_promptText != null) _promptText.text = "UFO Locked: Finish Pinball Phase First";
            }
            else
            {
                _showPrompt = false;
            }
        }
        else
        {
            _showPrompt = false;

            // フィーバータイムのカウントダウン
            if (_feverTimer > 0f)
            {
                _feverTimer -= Time.deltaTime;
                if (_feverTimer <= 0f)
                {
                    _feverTimer = 0f;
                    Debug.Log("[UFOCameraController] Fever Time Ended.");
                }
            }

            // プレイセッションがアクティブ、かつライトが点灯している場合のみカウントダウンを起動
            if (IsPlaySessionActive && IsPlaySpotlightActive)
            {
                // フィーバータイム中でない時のみタイマーを減少させる
                if (_feverTimer <= 0f)
                {
                    _playTimer -= Time.deltaTime;
                }

                if (_playTimer <= 0f)
                {
                    bool isBusy = _ufoController != null && _ufoController.IsBusy;
                    string stateStr = _ufoController != null ? _ufoController.CurrentState.ToString() : "NULL";
                    string nameStr = _ufoController != null ? _ufoController.name : "NULL";
                    
                    if (Time.frameCount % 30 == 0)
                    {
                        Debug.Log($"[UFOCameraController] Timer: {_playTimer:F2}, Controller: {nameStr}, IsBusy: {isBusy}, State: {stateStr}");
                    }

                    // Only end the session if the claw arm is not busy, or as a fail-safe if the timer is way negative (e.g. -10s)
                    if (_ufoController == null || !_ufoController.IsBusy || _playTimer <= -10f)
                    {
                        _playTimer = 0f;
                        IsPlaySessionActive = false;
                        SetPlaySpotlight(false);
                        _destroyedCoinCount = 0; // 反応数をリセット
                        Debug.Log("[UFOCameraController] UFO Catcher play session expired. Light off & Coin count reset.");
                    }
                }
            }
            else
            {
                // Waiting for payment: Spacebar shortcut to pay
                if (_paymentCount < maxPlayCount)
                {
                    float cost = GetCurrentPlayCost();
                    bool hasEnoughMoney = MoneyManager.Instance != null && MoneyManager.Instance.CurrentMoney >= cost;
                    if (hasEnoughMoney && Keyboard.current != null && Keyboard.current.spaceKey.wasPressedThisFrame)
                    {
                        PayAndStartPlay(cost);
                    }
                }
            }

            HandleUfoInput();
        }

        // 毎フレーム動的UIの状態を更新
        UpdateDynamicUI();

        // 警告音（残り時間10秒以下）の再生・停止管理
        UpdateWarningSound();
    }

    public int PaymentCount => _paymentCount;
    public float RemainingTime => _playTimer;

    public void ResetPaymentCount()
    {
        _paymentCount = 0;
    }

    public float GetCurrentPlayCost()
    {
        return playCostBase * Mathf.Pow(costIncreaseMultiplier, _paymentCount);
    }

    /// <summary>
    /// フィーバータイムを開始し、制限時間を指定秒数間ストップさせます。
    /// </summary>
    public void StartFeverTime(float duration)
    {
        _feverTimer = duration;
        Debug.Log($"[UFOCameraController] Fever Time Started for {duration} seconds!");
    }

    /// <summary>
    /// UFOキャッチャーの残り時間を seconds 秒延長する。
    /// スキルアイテム（時計）取得時などから呼び出す。
    /// </summary>
    public void AddPlayTime(float seconds)
    {
        if (!IsPlaySessionActive)
        {
            Debug.LogWarning("[UFOCameraController] AddPlayTime: ゲームセッションがアクティブではないため、時間延長をスキップします。");
            return;
        }
        _playTimer += seconds;
        if (_playTimer > 10f)
        {
            _hasPlayedLowTimeWarning = false; // 時間延長で10秒を超えた場合は警告音再生フラグをリセット
        }
        Debug.Log($"[UFOCameraController] 残り時間を {seconds}秒延長しました。現在の残り時間: {_playTimer:F1}秒");
    }

    private void PayAndStartPlay(float cost)
    {
        if (MoneyManager.Instance != null)
        {
            MoneyManager.Instance.ReduceMoney(cost);
        }
        _paymentCount++;
        _playTimer = playDuration;
        IsPlaySessionActive = true;
        _hasPlayedLowTimeWarning = false; // 新規セッション開始時に警告音再生フラグをリセット

        // 自動点灯を削除し、CoinDestroyerZoneに3回入るまで消灯状態を維持します。

        // コイン投入演出の開始（カウンターをリセットして1枚目を投入）
        _triggeredCoinCount = 0;
        TriggerCoinInsertionAnimation();

        // コイン投入音の再生
        PlaySound(coinInsertSound);

        Debug.Log($"[UFOCameraController] Started UFO play session. Cost: ¥{cost}, Limit: {playDuration}s, Total plays: {_paymentCount}");
    }

    /// <summary>
    /// コイン支払い時に、コインを出現させてDEVILCATCHERの中を指定座標間で移動し、物理落下させる演出コルーチン。
    /// </summary>
    private System.Collections.IEnumerator AnimateCoinInsertion()
    {
        GameObject activeCoinPrefab = coinPrefab;
        if (activeCoinPrefab == null)
        {
            // 自動フォールバック: ItemSpawner からゴールドコインのPrefabを探す
            if (ItemSpawner.Instance != null && ItemSpawner.Instance.goldCoinPrefab != null)
            {
                activeCoinPrefab = ItemSpawner.Instance.goldCoinPrefab;
            }
        }

        if (activeCoinPrefab == null)
        {
            Debug.LogWarning("[UFOCameraController] コイン投入演出用の coinPrefab がアタッチされておらず、自動取得も失敗したため演出をスキップします。");
            yield break;
        }

        // 親とする DEVILCATCHER オブジェクトをシーンから検索
        GameObject devilCatcher = GameObject.Find(devilCatcherName);
        if (devilCatcher == null)
        {
            // 表記揺れ対策
            devilCatcher = GameObject.Find("new_ufocatcher 1");
        }

        Transform parentTransform = devilCatcher != null ? devilCatcher.transform : null;

        // コインをインスタンス化
        GameObject coin = Instantiate(activeCoinPrefab);
        if (parentTransform != null)
        {
            // ローカル座標で動かすため親を設定
            coin.transform.SetParent(parentTransform, false);
        }

        // 初期座標・スケール・角度を設定
        coin.transform.localPosition = coinStartLocalPos;
        coin.transform.localScale = coinAnimationScale;
        coin.transform.localEulerAngles = coinAnimationRotation;

        // Rigidbodyを取得して一時的に物理挙動を無効化（Lerp移動させるため）
        Rigidbody rb = coin.GetComponent<Rigidbody>();
        bool originalKinematic = true;
        if (rb != null)
        {
            originalKinematic = rb.isKinematic;
            rb.isKinematic = true;
        }

        // 1秒間かけて Lerp 移動
        float elapsed = 0f;
        while (elapsed < coinAnimationDuration)
        {
            elapsed += Time.deltaTime;
            float t = Mathf.Clamp01(elapsed / coinAnimationDuration);
            coin.transform.localPosition = Vector3.Lerp(coinStartLocalPos, coinEndLocalPos, t);
            yield return null;
        }

        // 移動完了後、放す（isKinematicを元に戻して物理落下させる）
        if (rb != null)
        {
            rb.isKinematic = originalKinematic;
            rb.linearVelocity = Vector3.zero;
            rb.angularVelocity = Vector3.zero;
        }
    }

    /// <summary>
    /// 外部（TriggerSoundPlayerなど）からコイン投入演出を連動してトリガーする公開メソッド。
    /// 設定された上限回数（coinAnimationRepeatCount）に達するまで、1回ずつコインを投入します。
    /// </summary>
    public void TriggerCoinInsertionAnimation()
    {
        if (_triggeredCoinCount < coinAnimationRepeatCount)
        {
            StartCoroutine(AnimateCoinInsertion());
            _triggeredCoinCount++;
            Debug.Log($"[UFOCameraController] 連動コイン投入を実行しました。回数: {_triggeredCoinCount} / {coinAnimationRepeatCount}");
        }
        else
        {
            Debug.Log($"[UFOCameraController] 連動コイン投入は上限回数（{coinAnimationRepeatCount}回）に達しているため実行しません。");
        }
    }

    /// <summary>
    /// CoinDestroyerZoneでコインが破棄された際に呼び出されます。
    /// 3回反応するとライトを点灯します。
    /// </summary>
    public void NotifyCoinDestroyed()
    {
        _destroyedCoinCount++;
        Debug.Log($"[UFOCameraController] CoinDestroyerZone反応数: {_destroyedCoinCount} / 3");
        if (_destroyedCoinCount == 3)
        {
            SetPlaySpotlight(true);
        }
    }

    /// <summary>
    /// スポットライトおよびアタッチされたライト群、さらにUFOItemGoalのライト・マテリアルの有効/無効を一括設定します。
    /// 点灯（ON）時は徐々に速くなる点滅演出を行ってから完全点灯します。
    /// </summary>
    public void SetPlaySpotlight(bool active)
    {
        if (active)
        {
            // すでに点灯中・点灯演出中の二重起動を防ぐ
            if (IsPlaySpotlightActive) return;
            CacheOriginalLightIntensities(); // 元の強度をキャッシュ

            // ライト点滅開始の最初のタイミングで、起動音を末尾0.4秒カットして一度だけ流す
            if (lightFlickerSound != null)
            {
                PlayLightSoundWithTailCut(lightFlickerSound, lightFlickerVolume, 0.4f);
            }

            StartCoroutine(PlayLightOnFlickerCoroutine());
        }
        else
        {
            IsPlaySpotlightActive = false;
            ApplyRawLightsState(false);
            
            // 消灯音の再生（カットなしで最後まで流す）
            if (lightOffSound != null)
            {
                PlayLightSoundWithTailCut(lightOffSound, lightOffVolume, 0f);
            }
            Debug.Log("[UFOCameraController] ライトを消灯しました。");
        }
    }

    /// <summary>
    /// ライトオブジェクト群およびUFOItemGoalマテリアル・ライトの状態を明るさ倍率を適用して適用します。
    /// </summary>
    private void ApplyRawLightsState(bool active, float brightnessMultiplier = 1.0f)
    {
        if (playSpotlight != null)
        {
            playSpotlight.SetActive(active);
            if (active)
            {
                foreach (var light in playSpotlight.GetComponentsInChildren<Light>(true))
                {
                    if (light != null && _originalLightIntensities.TryGetValue(light, out float origInt))
                    {
                        light.intensity = origInt * brightnessMultiplier;
                        if (_originalLightRanges.TryGetValue(light, out float origRange))
                        {
                            light.range = origRange * brightnessMultiplier;
                        }
                    }
                }
            }
        }

        if (targetLights != null)
        {
            foreach (var lightObj in targetLights)
            {
                if (lightObj != null)
                {
                    lightObj.SetActive(active);
                    if (active)
                    {
                        foreach (var light in lightObj.GetComponentsInChildren<Light>(true))
                        {
                            if (light != null && _originalLightIntensities.TryGetValue(light, out float origInt))
                            {
                                light.intensity = origInt * brightnessMultiplier;
                                if (_originalLightRanges.TryGetValue(light, out float origRange))
                                {
                                    light.range = origRange * brightnessMultiplier;
                                }
                            }
                        }
                    }
                }
            }
        }

        var ufoGoal = FindAnyObjectByType<UFOItemGoal>();
        if (ufoGoal != null)
        {
            ufoGoal.SetInsertableItemsLights(active, brightnessMultiplier);
        }
    }

    /// <summary>
    /// 徐々に点滅が速くなりながら最終的に完全点灯するフリッカーコルーチン。
    /// 完全点灯した瞬間にタイマーのカウントダウンを開始します。
    /// </summary>
    private System.Collections.IEnumerator PlayLightOnFlickerCoroutine()
    {
        float duration = 1.8f;      // 演出時間を1.8秒に延長（+0.5秒）
        float elapsed = 0f;
        bool state = false;
        float minInterval = 0.03f;  // 後半の高速点滅の間隔
        float maxInterval = 0.22f;  // 前半の点滅間隔を0.35秒から0.22秒に逆補正（スピードアップ）

        while (elapsed < duration)
        {
            state = !state;

            // 経過時間割合(0〜1)に応じて明るさ倍率(0.15〜1.0)を算出
            float progress = elapsed / duration;
            float multiplier = Mathf.Lerp(0.15f, 1.0f, progress);

            // 点滅オン・オフに合わせて明るさ倍率を反映
            ApplyRawLightsState(state, multiplier);

            // 2乗のイージングをかけて、後半に向けて一気に加速させます
            float currentInterval = Mathf.Lerp(maxInterval, minInterval, progress * progress);

            yield return new WaitForSeconds(currentInterval);
            elapsed += currentInterval;
        }

        // 最終的に完全点灯状態にし、タイマーを起動
        ApplyRawLightsState(true, 1.0f);
        IsPlaySpotlightActive = true;
        Debug.Log("[UFOCameraController] ライト点滅演出が完了しました。常時点灯を開始しタイマーを起動します。");
    }

    private void OnMachineClicked()
    {
        if (IsPlayingUfo || _isTransitioning) return;

        bool canPlayUfo = RoundManager.Instance == null || RoundManager.Instance.CanPlayUfo();
        if (!canPlayUfo) return;

        StartCoroutine(TransitionToUfoCamera());
    }

    private System.Collections.IEnumerator TransitionToUfoCamera()
    {
        _isTransitioning = true;

        if (machineHover != null)
        {
            machineHover.enabled = false;
        }

        if (_fpController != null)
        {
            _fpController.enabled = false;
            _fpController.SetAvatarVisibility(false);
            var animator = _fpController.GetComponentInChildren<Animator>();
            if (animator != null)
            {
                animator.SetFloat("Speed", 0f);
            }
        }

        if (playerCamera != null)
        {
            _originalPlayerCamPos = playerCamera.transform.position;
            _originalPlayerCamRot = playerCamera.transform.rotation;
        }

        if (playerCamera != null && frontCamera != null)
        {
            Vector3 startPos = playerCamera.transform.position;
            Quaternion startRot = playerCamera.transform.rotation;
            Vector3 targetPos = frontCamera.transform.position;
            Quaternion targetRot = frontCamera.transform.rotation;

            float t = 0f;
            while (t < 1f)
            {
                t += Time.deltaTime / transitionDuration;
                float e = transitionEase.Evaluate(Mathf.Clamp01(t));
                playerCamera.transform.position = Vector3.Lerp(startPos, targetPos, e);
                playerCamera.transform.rotation = Quaternion.Slerp(startRot, targetRot, e);
                yield return null;
            }

            playerCamera.transform.position = targetPos;
            playerCamera.transform.rotation = targetRot;
        }

        _isTransitioning = false;
        EnterUfoMode();
    }

    private System.Collections.IEnumerator TransitionBackToPlayerCamera()
    {
        _isTransitioning = true;

        IsPlayingUfo = false;
        IsPlaySessionActive = false;
        if (playSpotlight != null)
        {
            playSpotlight.SetActive(false);
        }

        if (ufoUiCanvas != null)
        {
            ufoUiCanvas.SetActive(false);
        }
        if (_timerPanel != null) _timerPanel.SetActive(false);
        if (_paymentPanel != null) _paymentPanel.SetActive(false);

        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;

        if (playerCamera != null)
        {
            Camera activeCam = _activeCamera != null ? _activeCamera : frontCamera;
            if (activeCam != null)
            {
                playerCamera.transform.position = activeCam.transform.position;
                playerCamera.transform.rotation = activeCam.transform.rotation;
            }
            playerCamera.enabled = true;
        }

        if (frontCamera != null) frontCamera.enabled = false;
        if (leftCamera != null) leftCamera.enabled = false;
        if (rightCamera != null) rightCamera.enabled = false;
        if (topCamera != null) topCamera.enabled = false;

        if (_fpController != null)
        {
            _fpController.SetAvatarVisibility(true);
        }

        if (playerCamera != null)
        {
            Vector3 startPos = playerCamera.transform.position;
            Quaternion startRot = playerCamera.transform.rotation;

            float t = 0f;
            while (t < 1f)
            {
                t += Time.deltaTime / transitionDuration;
                float e = transitionEase.Evaluate(Mathf.Clamp01(t));
                playerCamera.transform.position = Vector3.Lerp(startPos, _originalPlayerCamPos, e);
                playerCamera.transform.rotation = Quaternion.Slerp(startRot, _originalPlayerCamRot, e);
                yield return null;
            }

            playerCamera.transform.position = _originalPlayerCamPos;
            playerCamera.transform.rotation = _originalPlayerCamRot;
        }

        if (_fpController != null)
        {
            _fpController.enabled = true;
        }

        var pickupController = FindAnyObjectByType<CupPickupController>();
        if (pickupController != null)
        {
            pickupController.enabled = true;
        }

        bool canPlayUfo = RoundManager.Instance == null || RoundManager.Instance.CanPlayUfo();
        if (machineHover != null)
        {
            machineHover.enabled = canPlayUfo;
        }

        _isTransitioning = false;
        Debug.Log("[UFOCameraController] Exit UFO mode completed.");
    }

    private void EnterUfoMode()
    {
        _paymentCount = 0;
        _playTimer = 0f;
        IsPlaySessionActive = false;
        if (playSpotlight != null)
        {
            playSpotlight.SetActive(false);
        }

        SetUfoMode(true);
        Debug.Log($"[UFOCameraController] EnterUfoMode: frontCamera={( frontCamera != null ? frontCamera.name + " display=" + frontCamera.targetDisplay : "NULL")}");
        Debug.Log($"[UFOCameraController] EnterUfoMode: leftCamera={(  leftCamera  != null ? leftCamera.name  : "NULL")}");
        Debug.Log($"[UFOCameraController] EnterUfoMode: rightCamera={( rightCamera != null ? rightCamera.name : "NULL")}");
        Debug.Log($"[UFOCameraController] EnterUfoMode: topCamera={(   topCamera   != null ? topCamera.name   : "NULL")}");
        SwitchUfoCameraTo(frontCamera);
    }

    private void ExitUfoMode()
    {
        if (_isTransitioning) return;
        StartCoroutine(TransitionBackToPlayerCamera());
    }

    private void SetUfoMode(bool active)
    {
        IsPlayingUfo = active;

        if (_fpController != null)
        {
            if (active)
            {
                // キャラクターの移動・回転アニメーションをリセットしてからスクリプトを停止する
                var animator = _fpController.GetComponentInChildren<Animator>();
                if (animator != null)
                {
                    animator.SetFloat("Speed", 0f);
                }
            }
            _fpController.enabled = !active;
            _fpController.SetAvatarVisibility(!active); // UFOプレイ中はキャラクターモデルを非表示にする
        }

        // UFOプレイ中以外は他インタラクション（カップ回収等）を無効化するため、CupPickupController も無効化
        var pickupController = FindAnyObjectByType<CupPickupController>();
        if (pickupController != null)
        {
            pickupController.enabled = !active;
        }

        // プレイヤーカメラとUFO UIの有効化/無効化
        if (playerCamera != null)
        {
            playerCamera.enabled = !active;
        }

        if (ufoUiCanvas != null)
        {
            ufoUiCanvas.SetActive(active);
        }

        // カーソルの表示状態を切り替え
        if (active)
        {
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;
        }
        else
        {
            Cursor.lockState = CursorLockMode.Locked;
            Cursor.visible = false;

            // 全てのUFOカメラを無効にする
            if (frontCamera != null) frontCamera.enabled = false;
            if (leftCamera  != null) leftCamera.enabled  = false;
            if (rightCamera != null) rightCamera.enabled = false;
            if (topCamera   != null) topCamera.enabled   = false;

            // スポットライトもオフにする
            if (playSpotlight != null) playSpotlight.SetActive(false);
        }
    }

    /// <summary>
    /// Display2のUFOカメラ間だけを切り替える。
    /// playerCamera（Display4）には一切触れない。
    /// </summary>
    private void SwitchUfoCameraTo(Camera targetCamera)
    {
        if (targetCamera == null)
        {
            Debug.LogError("[UFOCameraController] SwitchUfoCameraTo: targetCamera が null です！インスペクターでカメラを設定してください。");
            return;
        }

        // カメラのGameObjectが非アクティブな場合も有効化する
        if (!targetCamera.gameObject.activeInHierarchy)
        {
            targetCamera.gameObject.SetActive(true);
            Debug.LogWarning($"[UFOCameraController] {targetCamera.name} のGameObjectが非アクティブだったため有効化しました");
        }

        // UFOカメラ（Display2）だけを切り替える
        if (frontCamera != null) frontCamera.enabled = false;
        if (leftCamera  != null) leftCamera.enabled  = false;
        if (rightCamera != null) rightCamera.enabled = false;
        if (topCamera   != null) topCamera.enabled   = false;

        targetCamera.enabled = true;
        _activeCamera = targetCamera;

        Debug.Log($"[UFOCameraController] UFOカメラ切り替え → {targetCamera.name} / targetDisplay={targetCamera.targetDisplay} / enabled={targetCamera.enabled}");
    }

    private void HandleUfoInput()
    {
        if (Keyboard.current == null) return;

        // モード終了（F, Escape, Q）
        if (Keyboard.current.fKey.wasPressedThisFrame ||
            Keyboard.current.escapeKey.wasPressedThisFrame ||
            Keyboard.current.qKey.wasPressedThisFrame)
        {
            ExitUfoMode();
            return;
        }

        // 視点切り替えキー (1:前, 2:左, 3:右, 4:上)
        if (Keyboard.current.digit1Key.wasPressedThisFrame) SwitchUfoCameraTo(frontCamera);
        if (Keyboard.current.digit2Key.wasPressedThisFrame) SwitchUfoCameraTo(leftCamera);
        if (Keyboard.current.digit3Key.wasPressedThisFrame) SwitchUfoCameraTo(rightCamera);
        if (Keyboard.current.digit4Key.wasPressedThisFrame) SwitchUfoCameraTo(topCamera);
    }

    private void CreateDynamicUI()
    {
        // 1. Canvasの生成
        GameObject canvasGo = new GameObject("UFODynamicUICanvas", typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
        _dynamicCanvas = canvasGo.GetComponent<Canvas>();
        _dynamicCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
        _dynamicCanvas.sortingOrder = 31000;
        if (frontCamera != null)
        {
            _dynamicCanvas.targetDisplay = frontCamera.targetDisplay;
        }
        else
        {
            _dynamicCanvas.targetDisplay = 3; // デフォルト Display 4 (インデックス3)
        }

        CanvasScaler scaler = canvasGo.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        scaler.matchWidthOrHeight = 0.5f;

        // 2. Prompt Text
        GameObject promptGo = new GameObject("PromptText", typeof(RectTransform), typeof(TextMeshProUGUI));
        promptGo.transform.SetParent(canvasGo.transform, false);
        _promptText = promptGo.GetComponent<TextMeshProUGUI>();
        _promptText.fontSize = 28;
        _promptText.alignment = TextAlignmentOptions.Center;
        _promptText.color = Color.white;
        _promptText.text = "[F] Play UFO Catcher";
        
        RectTransform promptRt = promptGo.GetComponent<RectTransform>();
        promptRt.anchorMin = new Vector2(0.5f, 0f);
        promptRt.anchorMax = new Vector2(0.5f, 0f);
        promptRt.pivot = new Vector2(0.5f, 0f);
        promptRt.anchoredPosition = new Vector2(0f, 120f);
        promptRt.sizeDelta = new Vector2(600f, 60f);

        var shadow = promptGo.AddComponent<Shadow>();
        shadow.effectColor = new Color(0f, 0f, 0f, 0.75f);
        shadow.effectDistance = new Vector2(2f, -2f);

        // 3. 支払いパネルの生成
        _paymentPanel = new GameObject("PaymentPanel", typeof(RectTransform), typeof(Image));
        _paymentPanel.transform.SetParent(canvasGo.transform, false);
        
        Image panelImage = _paymentPanel.GetComponent<Image>();
        panelImage.color = new Color(0.1f, 0.1f, 0.1f, 0.85f);

        RectTransform panelRt = _paymentPanel.GetComponent<RectTransform>();
        panelRt.anchorMin = new Vector2(0.5f, 0.5f);
        panelRt.anchorMax = new Vector2(0.5f, 0.5f);
        panelRt.pivot = new Vector2(0.5f, 0.5f);
        panelRt.anchoredPosition = Vector2.zero;
        panelRt.sizeDelta = new Vector2(500f, 320f);

        // Title Text
        GameObject titleGo = new GameObject("TitleText", typeof(RectTransform), typeof(TextMeshProUGUI));
        titleGo.transform.SetParent(_paymentPanel.transform, false);
        TextMeshProUGUI titleText = titleGo.GetComponent<TextMeshProUGUI>();
        titleText.fontSize = 26;
        titleText.fontStyle = FontStyles.Bold;
        titleText.alignment = TextAlignmentOptions.Center;
        titleText.color = Color.white;
        titleText.text = "UFO Catcher Payment";

        RectTransform titleRt = titleGo.GetComponent<RectTransform>();
        titleRt.anchorMin = new Vector2(0.5f, 1f);
        titleRt.anchorMax = new Vector2(0.5f, 1f);
        titleRt.pivot = new Vector2(0.5f, 1f);
        titleRt.anchoredPosition = new Vector2(0f, -25f);
        titleRt.sizeDelta = new Vector2(460f, 40f);

        // ステータステキスト
        GameObject statusGo = new GameObject("StatusText", typeof(RectTransform), typeof(TextMeshProUGUI));
        statusGo.transform.SetParent(_paymentPanel.transform, false);
        _paymentStatusText = statusGo.GetComponent<TextMeshProUGUI>();
        _paymentStatusText.fontSize = 18;
        _paymentStatusText.alignment = TextAlignmentOptions.Center;
        _paymentStatusText.color = Color.white;

        RectTransform statusRt = statusGo.GetComponent<RectTransform>();
        statusRt.anchorMin = new Vector2(0.5f, 0.5f);
        statusRt.anchorMax = new Vector2(0.5f, 0.5f);
        statusRt.pivot = new Vector2(0.5f, 0.5f);
        statusRt.anchoredPosition = new Vector2(0f, 10f);
        statusRt.sizeDelta = new Vector2(460f, 120f);

        // 支払いボタン
        GameObject btnGo = new GameObject("PayButton", typeof(RectTransform), typeof(Image), typeof(UnityEngine.UI.Button));
        btnGo.transform.SetParent(_paymentPanel.transform, false);
        _payButton = btnGo.GetComponent<UnityEngine.UI.Button>();

        Image btnImg = btnGo.GetComponent<Image>();
        btnImg.color = new Color(0.2f, 0.6f, 0.2f, 1f);

        RectTransform btnRt = btnGo.GetComponent<RectTransform>();
        btnRt.anchorMin = new Vector2(0.5f, 0f);
        btnRt.anchorMax = new Vector2(0.5f, 0f);
        btnRt.pivot = new Vector2(0.5f, 0f);
        btnRt.anchoredPosition = new Vector2(0f, 75f);
        btnRt.sizeDelta = new Vector2(300f, 50f);

        GameObject btnTextGo = new GameObject("BtnText", typeof(RectTransform), typeof(TextMeshProUGUI));
        btnTextGo.transform.SetParent(btnGo.transform, false);
        _payButtonText = btnTextGo.GetComponent<TextMeshProUGUI>();
        _payButtonText.fontSize = 20;
        _payButtonText.fontStyle = FontStyles.Bold;
        _payButtonText.alignment = TextAlignmentOptions.Center;
        _payButtonText.color = Color.white;

        RectTransform btnTextRt = btnTextGo.GetComponent<RectTransform>();
        btnTextRt.anchorMin = Vector2.zero;
        btnTextRt.anchorMax = Vector2.one;
        btnTextRt.sizeDelta = Vector2.zero;

        _payButton.onClick.AddListener(() => {
            float cost = GetCurrentPlayCost();
            bool hasEnoughMoney = MoneyManager.Instance != null && MoneyManager.Instance.CurrentMoney >= cost;
            if (hasEnoughMoney && !IsPlaySessionActive && _paymentCount < maxPlayCount)
            {
                PayAndStartPlay(cost);
            }
        });

        // Close Guide Text
        GameObject closeTextGo = new GameObject("CloseText", typeof(RectTransform), typeof(TextMeshProUGUI));
        closeTextGo.transform.SetParent(_paymentPanel.transform, false);
        TextMeshProUGUI closeText = closeTextGo.GetComponent<TextMeshProUGUI>();
        closeText.fontSize = 16;
        closeText.alignment = TextAlignmentOptions.Center;
        closeText.color = Color.gray;
        closeText.text = "[F] Exit and Return";

        RectTransform closeTextRt = closeTextGo.GetComponent<RectTransform>();
        closeTextRt.anchorMin = new Vector2(0.5f, 0f);
        closeTextRt.anchorMax = new Vector2(0.5f, 0f);
        closeTextRt.pivot = new Vector2(0.5f, 0f);
        closeTextRt.anchoredPosition = new Vector2(0f, 25f);
        closeTextRt.sizeDelta = new Vector2(460f, 30f);

        // 4. タイマーパネルの生成
        _timerPanel = new GameObject("TimerPanel", typeof(RectTransform), typeof(Image));
        _timerPanel.transform.SetParent(canvasGo.transform, false);

        Image timerPanelImage = _timerPanel.GetComponent<Image>();
        timerPanelImage.color = new Color(0.1f, 0.1f, 0.1f, 0.8f);

        RectTransform timerPanelRt = _timerPanel.GetComponent<RectTransform>();
        timerPanelRt.anchorMin = new Vector2(0.5f, 1f);
        timerPanelRt.anchorMax = new Vector2(0.5f, 1f);
        timerPanelRt.pivot = new Vector2(0.5f, 1f);
        timerPanelRt.anchoredPosition = new Vector2(0f, -30f);
        timerPanelRt.sizeDelta = new Vector2(320f, 75f);

        // タイマーテキスト
        GameObject timerTextGo = new GameObject("TimerText", typeof(RectTransform), typeof(TextMeshProUGUI));
        timerTextGo.transform.SetParent(_timerPanel.transform, false);
        _timerText = timerTextGo.GetComponent<TextMeshProUGUI>();
        _timerText.fontSize = 20;
        _timerText.alignment = TextAlignmentOptions.Center;
        _timerText.color = Color.white;

        RectTransform timerTextRt = timerTextGo.GetComponent<RectTransform>();
        timerTextRt.anchorMin = Vector2.zero;
        timerTextRt.anchorMax = Vector2.one;
        timerTextRt.sizeDelta = Vector2.zero;

        // 初期非活性
        _promptText.gameObject.SetActive(false);
        _paymentPanel.SetActive(false);
        _timerPanel.SetActive(false);
    }

    private void UpdateDynamicUI()
    {
        if (_dynamicCanvas == null) return;

        if (_showPrompt)
        {
            _promptText.gameObject.SetActive(true);
            _paymentPanel.SetActive(false);
            _timerPanel.SetActive(false);
        }
        else if (IsPlayingUfo)
        {
            _promptText.gameObject.SetActive(false);

            if (IsPlaySessionActive)
            {
                _timerPanel.SetActive(true);
                _paymentPanel.SetActive(false);

                if (_timerText != null)
                {
                    float displayedTime = Mathf.Max(0f, _playTimer);
                    _timerText.text = $"Time Left: {displayedTime:F1}s\nPlays: {_paymentCount} / {maxPlayCount}";
                }
            }
            else
            {
                _timerPanel.SetActive(false);
                _paymentPanel.SetActive(true);

                if (_paymentCount >= maxPlayCount)
                {
                    _paymentStatusText.text = "Play limit reached for this session.\nPress [F] to exit.";
                    _payButton.gameObject.SetActive(false);
                }
                else
                {
                    _payButton.gameObject.SetActive(true);
                    float cost = GetCurrentPlayCost();
                    _paymentStatusText.text = $"Cost: ¥{cost:N0}\nRemaining Plays: {maxPlayCount - _paymentCount}\n({playDuration}s control time per play)\nPress [Space] to Pay";

                    bool hasEnoughMoney = MoneyManager.Instance != null && MoneyManager.Instance.CurrentMoney >= cost;
                    _payButton.interactable = hasEnoughMoney;
                    _payButtonText.text = hasEnoughMoney ? $"Pay to Play (¥{cost:N0})" : "Insufficient Funds";
                    
                    Image btnImg = _payButton.GetComponent<Image>();
                    if (btnImg != null)
                    {
                        btnImg.color = hasEnoughMoney ? new Color(0.2f, 0.6f, 0.2f, 1f) : new Color(0.5f, 0.5f, 0.5f, 1f);
                    }
                }
            }
        }
        else
        {
            _promptText.gameObject.SetActive(false);
            _paymentPanel.SetActive(false);
            _timerPanel.SetActive(false);
        }
    }

    private void UpdateWarningSound()
    {
        // UFOItemGoal.IsFlashing (アイテム演出中) は警告音を鳴らさない
        bool shouldPlay = IsPlaySessionActive && _playTimer > 0f && _playTimer <= 10f && !UFOItemGoal.IsFlashing;

        if (shouldPlay)
        {
            if (!_hasPlayedLowTimeWarning)
            {
                _hasPlayedLowTimeWarning = true;
                if (lowTimeWarningSound != null)
                {
                    if (audioSource == null)
                    {
                        audioSource = GetComponent<AudioSource>();
                        if (audioSource == null)
                        {
                            audioSource = gameObject.AddComponent<AudioSource>();
                            audioSource.playOnAwake = false;
                            audioSource.spatialBlend = 0f;
                        }
                    }
                    if (audioSource != null)
                    {
                        audioSource.clip = lowTimeWarningSound;
                        audioSource.loop = true;
                        audioSource.volume = soundVolume;
                        audioSource.Play();
                    }
                }
            }
        }
        else
        {
            if (_hasPlayedLowTimeWarning)
            {
                _hasPlayedLowTimeWarning = false;
                if (audioSource != null && audioSource.clip == lowTimeWarningSound)
                {
                    audioSource.Stop();
                    audioSource.clip = null;
                    audioSource.loop = false;
                }
            }
        }
    }

    private void OnDestroy()
    {
        if (_bgTexture != null)
        {
            Destroy(_bgTexture);
        }

        if (_dynamicCanvas != null)
        {
            Destroy(_dynamicCanvas.gameObject);
        }

        if (machineHover != null)
        {
            machineHover.OnClicked -= OnMachineClicked;
        }
    }

    private void PlaySound(AudioClip clip)
    {
        if (clip != null)
        {
            if (audioSource == null)
            {
                audioSource = GetComponent<AudioSource>();
                if (audioSource == null)
                {
                    audioSource = gameObject.AddComponent<AudioSource>();
                    audioSource.playOnAwake = false;
                    audioSource.spatialBlend = 0f; // 2D音響にして距離減衰を無視する
                }
            }
            audioSource.PlayOneShot(clip, soundVolume);
        }
    }

    private void OnDrawGizmosSelected()
    {
        Transform center = ufoCenterTransform != null ? ufoCenterTransform : transform;
        
        // シーンビューで可視化するための黄色のワイヤー球を描画
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(center.position, interactionDistance);

        // 中心点に小さな赤い球を描画して位置をわかりやすくする
        Gizmos.color = Color.red;
        Gizmos.DrawSphere(center.position, 0.1f);
    }

    /// <summary>
    /// プレイヤーのCharacterController（カプセル型コライダー）の表面から、UFOキャッチャーの中心までの最短距離を計算します。
    /// </summary>
    private float GetDistanceToPlayer(App.Player.FirstPersonController player, Vector3 ufoCenter)
    {
        if (player == null) return float.MaxValue;

        var cc = player.GetComponent<CharacterController>();
        if (cc == null)
        {
            // CharacterControllerが見つからない場合は、プレイヤーの原点座標からの距離を返します
            return Vector3.Distance(player.transform.position, ufoCenter);
        }

        // プレイヤーのCharacterControllerのワールド空間における中心座標を計算
        Vector3 playerPos = player.transform.position;
        Vector3 capsuleCenter = playerPos + cc.center;
        
        // カプセルの円筒部分（上下の半球の中心を結ぶ線分）の半分の長さを計算
        float halfSegLength = Mathf.Max(0f, (cc.height * 0.5f) - cc.radius);

        // カプセルの上部球体中心と下部球体中心のワールド座標
        Vector3 pBottom = capsuleCenter + Vector3.down * halfSegLength;
        Vector3 pTop = capsuleCenter + Vector3.up * halfSegLength;

        // カプセルの中心線分（pBottom -> pTop）上で、ufoCenterに最も近い点を求める
        Vector3 segmentDirection = pTop - pBottom;
        float segmentLength = segmentDirection.magnitude;
        if (segmentLength < 0.0001f)
        {
            float dist = Vector3.Distance(pBottom, ufoCenter) - cc.radius;
            return Mathf.Max(0f, dist);
        }

        Vector3 segmentDirNormal = segmentDirection / segmentLength;
        float t = Vector3.Dot(ufoCenter - pBottom, segmentDirNormal);
        t = Mathf.Clamp(t, 0f, segmentLength);
        Vector3 closestPointOnSegment = pBottom + segmentDirNormal * t;

        // 最寄りの点からufoCenterまでの距離を求め、コライダー半径を引くことでカプセル表面からの最短距離を算出
        float distanceToSurface = Vector3.Distance(closestPointOnSegment, ufoCenter) - cc.radius;
        return Mathf.Max(0f, distanceToSurface);
    }
}
